apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: talibro/weather:latest
          ports:
            - containerPort: 5000
          
